<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0524</FileVersion>
    <VersionPrefix>$(AssemblyVersion)</VersionPrefix>
  </PropertyGroup>

  <!--NuGet properties-->
  <PropertyGroup>
    <Title>Sumapap.Ddd.Mediator</Title>
    <PackageId>Sumapap.Ddd.Mediator</PackageId>
    <PackageTags>Sumapap;DDD;Mediator</PackageTags>
    <Description>
      This package implements the Adapter Pattern to allow IDomainEvent instances (defined in your Domain Entities) to be dispatched seamlessly through MediatR. This ensures your Domain Layer remains free of external dependencies while allowing your Application Layer to leverage standard `INotificationHandlerT` implementations.
    </Description>
    <PackageReadmeFile>docs\Sumapap.Ddd.Mediator.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\docs\Sumapap.Ddd.Mediator.md" Pack="true" PackagePath="docs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sumapap.Ddd\Sumapap.Ddd.csproj" />
  </ItemGroup>

</Project>
