<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0524</FileVersion>
    <VersionPrefix>$(AssemblyVersion)</VersionPrefix>
  </PropertyGroup>

  <!--NuGet properties-->
  <PropertyGroup>
    <Title>Sumapap.Persistence.Abstractions</Title>
    <PackageId>Sumapap.Persistence.Abstractions</PackageId>
    <PackageTags>Sumapap;Persistence;Abstractions</PackageTags>
    <Description>
      This package contains the abstractions for the persistence layer of the Sumapap application. It defines the interfaces and contracts that must be implemented by any persistence provider used in the application. The abstractions include repositories, unit of work, and other related components that facilitate data access and manipulation while maintaining a clean separation of concerns between the application logic and the underlying data storage mechanism.
    </Description>
    <PackageReadmeFile>docs\Sumapap.Persistence.Abstractions.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\docs\Sumapap.Persistence.Abstractions.md" Pack="true" PackagePath="docs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sumapap.Queries\Sumapap.Queries.csproj" />
  </ItemGroup>

</Project>
