<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.3.0</AssemblyVersion>
    <FileVersion>1.3.0.0402</FileVersion>
    <VersionPrefix>$(AssemblyVersion)</VersionPrefix>
  </PropertyGroup>

  <!--NuGet properties-->
  <PropertyGroup>
    <Title>Sumapap.Queries.Execution</Title>
    <PackageId>Sumapap.Queries.Execution</PackageId>
    <PackageTags>Sumapap;Queries;Execution</PackageTags>
    <Description>
      Utility for building dynamic queries, filtering, and sorting logic within the persistence layer.
    </Description>
    <PackageReadmeFile>docs\Sumapap.Queries.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\docs\Sumapap.Queries.md" Pack="true" PackagePath="docs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sumapap.Queries\Sumapap.Queries.csproj" />
  </ItemGroup>

</Project>
