<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0404</FileVersion>
    <VersionPrefix>$(AssemblyVersion)</VersionPrefix>
  </PropertyGroup>

  <!--NuGet properties-->
  <PropertyGroup>
    <Title>Sumapap.Persistence</Title>
    <PackageId>Sumapap.Persistence.EfCore</PackageId>
    <PackageTags>Sumapap;Persistence;Repository;EfCore</PackageTags>
    <Description>
      `Sumapap.Persistence.EfCore` implements ReadWriteRepository and Unit of Work abstraction using `EntityFrameworkCore`.
    </Description>
    <PackageReadmeFile>docs\Sumapap.Persistence.EfCore.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\docs\Sumapap.Persistence.EfCore.md" Pack="true" PackagePath="docs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sumapap.Persistence\Sumapap.Persistence.csproj" />
    <ProjectReference Include="..\Sumapap.Queries.Execution.EfCore\Sumapap.Queries.Execution.EfCore.csproj" />
  </ItemGroup>

</Project>
