<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<AssemblyVersion>1.0.1</AssemblyVersion>
		<FileVersion>1.0.1.0524</FileVersion>
		<VersionPrefix>$(AssemblyVersion)</VersionPrefix>
	</PropertyGroup>

	<!--NuGet properties-->
	<PropertyGroup>
		<Title>Sumapap.Navigations</Title>
		<PackageId>Sumapap.Navigations</PackageId>
		<PackageTags>Sumapap;Navigations</PackageTags>
		<Description>
      The `Sumapap.Navigations` package provides a set of tools and abstractions for implementing navigation functionality in your applications. It includes features such as page routing, navigation stacks, and integration with various UI frameworks. With Sumapap.Navigations, you can easily manage your application's navigation flow while maintaining a clean and modular architecture.
    </Description>
		<PackageReadmeFile>docs\Sumapap.Navigations.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\docs\Sumapap.Navigations.md" Pack="true" PackagePath="docs" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Sumapap.DependencyInjection\Sumapap.DependencyInjection.csproj" />
	</ItemGroup>
  
</Project>
