<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.1</AssemblyVersion>
    <FileVersion>1.0.1.0524</FileVersion>
    <VersionPrefix>$(AssemblyVersion)</VersionPrefix>
  </PropertyGroup>

  <!--NuGet properties-->
  <PropertyGroup>
    <Title>Sumapap.Ddd.Dispatcher</Title>
    <PackageId>Sumapap.Ddd.Dispatcher</PackageId>
    <PackageTags>Sumapap;DDD;Dispatcher</PackageTags>
    <Description>
      Core Domain-Driven Design (DDD) abstractions for the Sumapap ecosystem.
      Provides essential building blocks including Entity base classes, Value Objects, Aggregate Roots, and Domain Event interfaces to enforce clean separation of concerns and rich domain modeling in .NET applications.
    </Description>
    <PackageReadmeFile>docs\Sumapap.Ddd.Dispatcher.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\docs\Sumapap.Ddd.Dispatcher.md" Pack="true" PackagePath="docs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sumapap.Ddd.Abstractions\Sumapap.Ddd.Abstractions.csproj" />
  </ItemGroup>

</Project>