<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AssemblyVersion>3.0.0</AssemblyVersion>
    <FileVersion>3.0.0.0524</FileVersion>
    <VersionPrefix>$(AssemblyVersion)</VersionPrefix>
  </PropertyGroup>

  <!--NuGet properties-->
  <PropertyGroup>
    <Title>Sumapap.Ddd</Title>
    <PackageId>Sumapap.Ddd</PackageId>
    <PackageTags>Sumapap;DDD;Dispatcher</PackageTags>
    <Description>
      This package provides a simple, convention-based Domain Event Dispatcher that automatically discovers and invokes all registered `IDomainEventHandlerT` implementations for any given `IDomainEvent`. By leveraging .NET's built-in dependency injection, it ensures seamless integration with your application's service container, allowing for clean separation of concerns and adherence to DDD principles without coupling your domain layer to specific frameworks.
    </Description>
    <PackageReadmeFile>docs\Sumapap.Ddd.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\docs\Sumapap.Ddd.md" Pack="true" PackagePath="docs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sumapap.Ddd.Abstractions\Sumapap.Ddd.Abstractions.csproj" />
    <ProjectReference Include="..\Sumapap.DependencyInjection\Sumapap.DependencyInjection.csproj" />
  </ItemGroup>

</Project>