<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0513</FileVersion>
    <VersionPrefix>$(AssemblyVersion)</VersionPrefix>
  </PropertyGroup>

  <!--NuGet properties-->
  <PropertyGroup>
    <Title>Sumapap.Persistence.DependencyInjection</Title>
    <PackageId>Sumapap.Persistence.DependencyInjection</PackageId>
    <PackageTags>Sumapap;Persistence;DependencyInjection;DI</PackageTags>
    <Description>
      `Sumapap.Persistence.DependencyInjection` provides fluent dependency injection builders and extensions for configuring Sumapap.Persistence repositories and caching.
    </Description>
    <PackageReadmeFile>docs\Sumapap.Persistence.DependencyInjection.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\docs\Sumapap.Persistence.DependencyInjection.md" Pack="true" PackagePath="docs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sumapap.DependencyInjection\Sumapap.DependencyInjection.csproj" />
    <ProjectReference Include="..\Sumapap.Persistence.Abstractions\Sumapap.Persistence.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sumapap.Persistence.Caching" />
    <InternalsVisibleTo Include="Sumapap.Persistence.Caching.FusionCache" />
    <InternalsVisibleTo Include="Sumapap.Persistence.EfCore" />
  </ItemGroup>

</Project>
